### ISSUE TITLE
a question about the version used.

### ISSUE THREAD

**Issue by squoosh4** [Miepee/AM2R-Autopatcher-Mac#5]
what version does this patcher update to? is it the latest version?

**Comment by Miepee** [comment]
At the time of writing, 1.5.5 which right now is the latest version.
This does not have any auto-updater function and earlier versions than 1.5.5 are not available right now. 
EDIT: I've opened discussions now, so that people don't have to open issues for simple questions, if you have any other questions, feel free to open them there.
https://github.com/Miepee/AM2R-Autopatcher-Mac/discussions

**Comment by squoosh4** [comment]
alright thanks
